[package]
name = "noxious-core"
version = "0.1.0"
authors = ["Oguz Bilgener <oguz@bilgener.me>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["sync"] }
serde_json = "^1.0.62"
serde = "^1.0.123"
serde_derive = "^1.0.123"
