[package]
name = "noxious-server"
version = "0.1.0"
authors = ["Oguz Bilgener <oguz@bilgener.me>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["macros", "sync", "net", "rt-multi-thread", "signal"] }
noxious = { path = "../core" }
warp = "0.3.0"
chrono = "0.4.19"
