on:
  repository_dispatch:
    types: [build-artifacts]

name: Build Artifacts

jobs:

  build_image_and_publish:
    name: Build and Publish Docker Image
    if: github.event.client_payload.tag != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refs/tags/${{ github.event.client_payload.tag }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: olegtarasov/get-tag@v2.1
        name: Get Tag Name
        id: tagName
        # with:
        #   tagRegex: "noxious-(.*)"
        #   tagRegexGroup: 1

      - name: Print Tag
        run: echo "${{ steps.tagName.outputs.tag }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
            #,linux/arm64
          # tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags') }}
          tags: |
            oguzbilgener/noxious:latest
            oguzbilgener/noxious:${{ steps.tagName.outputs.tag }}
            ghcr.io/oguzbilgener/noxious:latest
            ghcr.io/oguzbilgener/noxious:${{ steps.tagName.outputs.tag }}
          # TODO: support tags for sub projects
